name: CI

on:
  push:
    branch:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golang-cilint
        uses: actions-contrib/golangci-lint@v1
